### ISSUE TITLE
Flashing and Flickering Issue

### ISSUE THREAD

**Issue by Serhii-Hulko** [adbloomandrew/teachparttime#18]
Hello @davidgatti. We noticed that page is flashing on loading. I think the issue is based on using this script. 
```
<script type="text/javascript">
            var css = 'dev';
            if(document.location.hostname == 'potato.teachpart-time.com')
            {
                css = 'potato';
            }
            var head  = document.getElementsByTagName('head')[0];
            var link  = document.createElement('link');
            link.rel  = 'stylesheet';
            link.href = './assets/css/' + css + '.css';
            head.appendChild(link);
		</script>
```
because we load styles after html, svg scripts etc. It will be looks worse when we will try to load page on 3g speed. If we load styles normally in head, there are no any flickering or other issues related to styles and images. Do we really need to choose css file depending on url address? It looks strange

**Comment by davidgatti** [comment]
@Serhii-Hulko we don't need to do anything ;) @aabony wanted to have the possibility to have different CSS, based on the domain, this way we can use one code base but let clients have different styles for their own implementations. 

Since we are doing everything in the front end this is right now the approach that I choose. I'm open to suggestions. 

I was thinking maybe we could do something like this:

"https://example.com" + (function(){ code }) + ".css"

Do you think this will work?

**Comment by Serhii-Hulko** [comment]
I think it's not the best approach. I think, the most of styles will be the same on both websites, so we can use dev.css on both websites normally and load potato.css to overwrite some styles. What do you think about it?

**Comment by davidgatti** [comment]
Just to make sure: potato is just a test - right? 😅 a way to test if this works. 

Regarding your solution, so your saying that we would have the main CSS, that have the majority fo the style in place, then we just dynamically load a small file that will change the base of the style based on the customer needs.

Correct?

**Comment by Serhii-Hulko** [comment]
yep

**Comment by Serhii-Hulko** [comment]
in this case we shouldn't have issues with flashing website

**Comment by Serhii-Hulko** [comment]
in other case we can use another html file which will load one css file else

**Comment by davidgatti** [comment]
OK, lets see. Before you do any changes, check out this PR #19

**Comment by Serhii-Hulko** [comment]
@aabony so, do we really need to use different styles based on domain?

**Comment by aabony** [comment]
well, here is what we are trying to accomplish: 
1) we will launch other sites like qkids.teachpartitme.com (where we replace qkids with something like Disney or VIPkid) 
2) we would like to use the code we have built to launch our other site, teachparttime.com (active here -> https://teachparttime.herokuapp.com/)

So im not sure what the best solution is, we do need to fix the flickering. If its easier, lets just duplicate the site each time we need to make a new site, instead of using one site and loading a different css file by domain? the flickering sucks

**Comment by davidgatti** [comment]
Another solution would be to have the site the plain old fashion way, hosted for example on Heroku, and use NodeJS to deliver it. Then the CSS URL can be replaced in the back-end before the user receives the site, and so they will get the right URL - and no flickering.

Right now the flickering is because we are joining everything in the front-end. To convert this to a NodeJS app should take less then 2h, and we can also set it up for auto deployment when new code gets in to the master branch, and also we can take advantage of the Heroku pipeline to develop and test new versions.

**Comment by aabony** [comment]
@davidgatti  @Serhii-Hulko if using heroku will get rid of the flickering, and it wont change any of our back-end setup, then lets do that. 2 hours is fine. Let me know what you guys think is best and lets move forward.

**Comment by Serhii-Hulko** [comment]
@aabony As for me, If we shouldn't use any backend functionality for this project, the best way is using simple css loading in head of html document. But if we need to do something else on backend side then we can use loading css files using nodejs.

**Comment by davidgatti** [comment]
Conversion to NodeJS app on Heroku is done.
